name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  desktop:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Configure (CMake)
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - name: Build (CMake)
        run: cmake --build build --config Release --parallel
      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.os }}
          path: build/Release/
